### ISSUE TITLE
Project Link

### ISSUE THREAD

**Issue by tahseenzahra** [tahseenzahra/spaceTravelers-react#22]
[Project Link](https://github.com/tahseenzahra/spaceTravelers-react/projects/1)

We are 3 participants who will be working on this project 
- [Tahseen Zahra](https://github.com/tahseenzahra)
- [Khaled-Al-Khateeb](https://github.com/Khaled-AlKhateeb)
- [Ashenafi Endashaw](https://github.com/Ashe546)

**Comment by OLIPLICHE** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- There is the link to the GitHub issue that has a link to the GitHub project 👍 
- Information about the number of people in their group has been provided 👍 

## Required Changes ♻️

- [ ] Please make sure the number of cards in the Backlog should be equal to 24
- [ ] Make sure that all cards are assigned to team members. there must be a circle with the user's avatar on each card: See Example bellow
- 
![Capture](https://user-images.githubusercontent.com/63972670/203085564-a32c5f08-43f3-4a1e-b5c8-e2554377152b.PNG) 

- **Here is yours, Please fix the mistake** 👇 

![Capture1](https://user-images.githubusercontent.com/63972670/203085918-efc2d5f0-3e65-4ac5-a436-1ddabfa46eac.PNG)

- Make sure to assign the name of each student (`assignee:<STUDENT USERNAME>`)

![as](https://user-images.githubusercontent.com/63972670/203089043-4099f257-59c6-41e6-94ca-d20a8b4faae8.PNG)
- Makes sure each student has cards with all required categories in their titles:

 Required categories:`Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters`


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Reem-lab** [comment]
# Hi Team

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Great on asign some tasks 🎉🔥

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] I can't see that you added to your kanban board the cards as required be the previous code reveiwer so kindly add the 24 cards to your kanban since you are team of three people 🔥♻
![image](https://user-images.githubusercontent.com/58553711/203323985-e53d0959-33a5-4f55-a1a7-85a00f215658.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tahseenzahra** [comment]
@Reem-lab 
![reviewer](https://user-images.githubusercontent.com/54817285/203326187-2658dcb1-d848-475f-acd1-612865ce7aa0.png)

https://github.com/tahseenzahra/spaceTravelers-react/projects/1
